#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  3 13:55:00 2020

@author: kelleclark
"""

import os
textfiles = [f for f in os.listdir('Test Data/short test data') if '.txt' in f]
corpus=[]
for f in textfiles:
    file =open('Test Data/short test data/'+f,'rt')
    corpus.append(file.read())
    file.close()
print(corpus)