#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 10:04:32 2020

@author: kelleclark
"""

# enumerate ngrams
def ngrams(input, n):
    # split delimiter is space
    input = input.split(' ')
    # create an empty dictionary
    output = {}
    
    for i in range(len(input) - n + 1):
        # generate an ngram
        g = ' '.join(input[i:i+n])
        # set output[key] = 0, if key is not already in dictionary; otherwise, no effect
        output.setdefault(g, 0)
        # increment the ngram count
        output[g] += 1
    
    # return the dictionary of ngrams (includes frequency of occurrence)
    return output